### ISSUE TITLE
need setting for focusing, sharpness, and etc

### ISSUE THREAD

**Issue by Chandralim** [Schibum/barcode.js#11]
do you have any function or what to do if i want the focus is more then before or... can we set the quality ?

**Comment by Schibum** [comment]
It currently does not use the new image capture API (https://www.w3.org/TR/image-capture/) so there is no focus control. Feel free to submit a PR though.

**Comment by Chandralim** [comment]
So can you tell me how to add that so i can use the control...thanks before
