### ISSUE TITLE
IOS browser not supported

### ISSUE THREAD

**Issue by amitramoliya** [Schibum/barcode.js#14]
We found that it's working perfectly on any Android browser but it is not working with IOS browsers.
Kindly provide us solution if it is available.

**Comment by Schibum** [comment]
PR welcome

**Comment by amitramoliya** [comment]
Means?

**Comment by dsanders11** [comment]
@amitramoliya, he meant a 'pull request' is welcome if you have a fix.

However, there's nothing which can be done here for the moment. [Safari does not support getting the webcam stream in JavaScript](http://caniuse.com/#search=getusermedia).

It looks like support many exist in Safari 11.
