### ISSUE TITLE
Could not find the repo via google

### ISSUE THREAD

**Issue by SimonKlausLudwig** [Schibum/barcode.js#16]
Hello.. this is not really an issue but I want to tell it anyway. Recently I was looking for a QR-Code-Scanner.. I typed in 'qr code scanner javascript' in google and found many of them. 

But they are not as good as yours.. 

So my advice is to rename the library to qrwhatever.js .. I think you would get many more stars..

I only found this library because I wrote to the owner from https://www.the-qrcode-generator.com/scan

BTW: Thank you for this awesome library... I hope this library will support also IOS. Since ios 11 its also possible to get the camera input.. Sorry for my bad english :P

**Comment by Schibum** [comment]
sry, don't care about stars
