### ISSUE TITLE
True Start/Stop For ContinuousScanner

### ISSUE THREAD

**Issue by dsanders11** [Schibum/barcode.js#3]
It would be great if there was true start/stop support for ContinuousScanner. Currently `setStopped` will stop the scanning (and freeze the webcam) but leave the webcam light on and the last image rendered to the scanner element.

Ideally ContinuousScanner would have a true start/stop which would:

- [ ] Turn on/off the webcam light (looks like it would require destroying the MediaStreamTrack to force the webcam light off)

- [ ] Hide the rendered image instead of leaving it frozen as the last image when disabled, like before render was called

The first one is the more important of the two, as users are uncomfortable with the webcam light staying on after whatever they needed to scan the QR code for is done. If it is part of a larger page, the webcam light may stay on a while, and is quite noticeable.

I'm willing to help with the changes, but I'm not familiar with the code yet so I figured I would create an issue first.

**Comment by Schibum** [comment]
Hi,
dispose() might be what you are looking for. It's supposed to stop the stream / cleanup all other resources. You'll have to recreate the instance to scan again though.

**Comment by dsanders11** [comment]
I tested `dispose()`, and while it makes the rendered stream disappear, the webcam light stays on. If I use a breakpoint at where I want to stop the feed and use `scanner.capturer_.stream_.getTracks()[0].stop();` that turns off the webcam light.

In my testing this is on the latest Chrome running on OS X.
